experiment:
  name: "Segformer_ADE20k"
  output_dir: "./checkpoints"
  log_dir: "./logs"

dataset:
  name: "ADE20K"
  data_root: "/kaggle/input/datasets/awsaf49/ade20k-dataset/ADEChallengeData2016"
  batch_size: 2
  num_workers: 4
  pin_memory: true
  img_size: [512, 512]
  augment: true
  scale_range: [0.5, 2.0]
  flip_prob: 0.5

model:
  student: "segformer_b4"
  student_pretrained_encoder: "nvidia/mit-b4"
  num_classes: 150
  student_checkpoint: null

train:
  max_iters: 32000
  eval_interval: 8000
  log_interval: 20

  optimizer: "AdamW"
  lr: 0.00006
  weight_decay: 0.01
  betas: [0.9, 0.999]

  head_lr_mult: 10.0
  connector_lr_mult: 10.0

  warmup_iters: 1500
  warmup_ratio: 1.0e-6
  poly_power: 1.0
